language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
#   - rbx-19mode
gemfile: Gemfile
before_script:
  - export USE_BUNDLER=yes
  - bundle exec rake db:drop
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake db:seed
  - bundle exec rake db:test:prepare
script:
  - bundle exec rake test TEST=test/unit/changelog_test.rb
  - bundle exec rake test TEST=test/functional/change_log_controller_test.rb
  - bundle exec rake test TEST=test/functional/homepage_controller_test.rb
  - bundle exec rake test TEST=test/functional/atom_feed_controller_test.rb
  - bundle exec rake test TEST=test/unit/helpers/atom_feed_helper_test.rb
  - bundle exec rake test TEST=test/unit/feed_post_test.rb